export const KINDS = Object.freeze({ Primary: 'primary', Secondary: 'secondary', Tertiary: 'tertiary' }) as const;
export const SIZES = Object.freeze({ Small: 'small', Medium: 'medium', Large: 'large' }) as const;
export const SHAPES = Object.freeze({ Square: 'square', Circle: 'circle' }) as const;
export const TYPES = Object.freeze({ Default: 'default', Compact: 'compact', Mini: 'mini' }) as const;
export const ORIENTATIONS = Object.freeze({Row: 'row', RowReverse: 'row-reverse', Column: 'column',
    ColumnReverse: 'column-reverse'}) as const;
export const ICONS = Object.freeze({ None: 'no-icon', Activity: 'activity', Airplay: 'airplay', AlertCircle: 'alert-circle',
    AlertOctagon: 'alert-octagon', AlertTriangle: 'alert-triangle', AlignCenter: 'align-center',
    AlignJustify: 'align-justify', AlignLeft: 'align-left', AlignRight: 'align-right', Anchor: 'anchor',
    Aperture: 'aperture', Archive: 'archive', ArrowDownCircle: 'arrow-down-circle', ArrowDownLeft: 'arrow-down-left',
    ArrowDownRight: 'arrow-down-right', ArrowDown: 'arrow-down', ArrowLeftCircle: 'arrow-left-circle',
    ArrowLeft: 'arrow-left', ArrowRightCircle: 'arrow-right-circle', ArrowRight: 'arrow-right',
    ArrowUpCircle: 'arrow-up-circle', ArrowUpLeft: 'arrow-up-left', ArrowUpRight: 'arrow-up-right', ArrowUp: 'arrow-up',
    AtSign: 'at-sign', Award: 'award', BarChart: 'bar-chart', BarChart2: 'bar-chart-2',
    BatteryCharging: 'battery-charging', Battery: 'battery', BellOff: 'bell-off', Bell: 'bell', Bluetooth: 'bluetooth',
    Bold: 'bold', BookOpen: 'book-open', Book: 'book', Bookmark: 'bookmark', Box: 'box', Briefcase: 'briefcase',
    Calendar: 'calendar', CameraOff: 'camera-off', Camera: 'camera', Cast: 'cast', CheckCircle: 'check-circle',
    CheckSquare: 'check-square', Check: 'check', ChevronDown: 'chevron-down', ChevronLeft: 'chevron-left',
    ChevronRight: 'chevron-right', ChevronUp: 'chevron-up', ChevronsDown: 'chevron-down', ChevronsLeft: 'chevron-left',
    ChevronsRight: 'chevron-right', ChevronsUp: 'chevron-up', Chrome: 'chrome', Circle: 'circle', Clipboard: 'clipboard',
    Clock: 'clock', CloudDrizzle: 'cloud-drizzle', CloudLightning: 'cloud-lightning', CloudOff: 'cloud-off',
    CloudRain: 'cloud-rain', CloudSnow: 'cloud-snow', Cloud: 'cloud', Code: 'code', Codepen: 'codepen',
    Codesandbox: 'codesandbox', Coffee: 'coffee', Columns: 'columns', Command: 'command', Compass: 'compass', Copy: 'copy',
    CornerDownLeft: 'corner-down-left', CornerDownRight: 'corner-down-right', CornerLeftDown: 'corner-left-down',
    CornerLeftUp: 'corner-left-up', CornerRightDown: 'corner-right-down', CornerRightUp: 'corner-right-up',
    CornerUpLeft: 'corner-up-left', CornerUpRight: 'corner-up-right', Cpu: 'cpu', CreditCard: 'credit-card', Crop: 'crop',
    Crosshair: 'crosshair', Database: 'database', Delete: 'delete', Disc: 'disc', DivideCircle: 'divide-circle',
    DivideSquare: 'divide-square', Divide: 'divide', DollarSign: 'dollar-sign', DownloadCloud: 'download-cloud',
    Download: 'download', Dribbble: 'dribbble', Droplet: 'droplet', Edit: 'edit', Edit2: 'edit2', Edit3: 'edit3',
    ExternalLink: 'external-link', EyeOff: 'eye-off', Eye: 'eye', Facebook: 'facebook', FastForward: 'fast-forward',
    Feather: 'feather', Figma: 'figma', FileMinus: 'file-minus', FilePlus: 'file-plus', FileText: 'file-text', File: 'file',
    Film: 'film', Filter: 'filter', Flag: 'flag', FolderMinus: 'folder-minus', FolderPlus: 'folder-plus', Folder: 'folder',
    Framer: 'framer', Frown: 'frown', Gift: 'gift', GitBranch: 'git-branch', GitCommit: 'git-commit', GitMerge: 'git-merge',
    GitPullRequest: 'git-pull-request', GitHub: 'github', Gitlab: 'gitlab', Globe: 'globe', Grid: 'grid',
    HardDrive: 'hard-drive', Hash: 'hash', Headphones: 'headphones', Heart: 'heart', HelpCircle: 'help-circle',
    Hexagon: 'hexagon', Home: 'home', Image: 'image', Inbox: 'inbox', Info: 'info', Instagram: 'instagram', Italic: 'italic',
    Key: 'key', Layers: 'layers', Layout: 'layout', LifeBuoy: 'life-buoy', Link: 'link', Link2: 'link-2',
    Linkedin: 'linkedin', List: 'list', Loader: 'loader', Lock: 'lock', LogIn: 'log-in', LogOut: 'log-out', Mail: 'mail',
    MapPin: 'map-pin', Map: 'map', Maximize: 'maximize', Maximize2: 'maximize-2', Meh: 'meh', Menu: 'menu',
    MessageCircle: 'message-circle', MessageSquare: 'message-square', MicOff: 'mic-off', Mic: 'mic',
    Minimize: 'minimize', Minimize2: 'minimize-2', MinusCircle: 'minus-circle', MinusSquare: 'minus-square', Minus: 'minus',
    Monitor: 'monitor', Moon: 'moon', MoreHorizontal: 'more-horizontal', MoreVertical: 'more-vertical',
    MousePointer: 'mouse-pointer', Move: 'move', Music: 'music', Navigation: 'navigation', Navigation2: 'navigation-2',
    Octagon: 'octagon', Package: 'package', Paperclip: 'paperclip', PauseCircle: 'pause-circle', Pause: 'pause',
    PenTool: 'pen-tool', Percent: 'percent', PhoneCall: 'phone-call', PhoneForwarded: 'phone-forwarded',
    PhoneIncoming: 'phone-incoming', PhoneMissed: 'phone-missed', PhoneOff: 'phone-off', PhoneOutgoing: 'phone-outgoing',
    Phone: 'phone', PieChart: 'pie-chart', PlayCircle: 'play-circle', Play: 'play', PlusCircle: 'plus-circle',
    PlusSquare: 'plus-square', Plus: 'plus', Pocket: 'pocket', Power: 'power', Printer: 'printer', Radio: 'radio',
    RefreshCcw: 'refresh-ccw', RefreshCw: 'refresh-cw', Repeat: 'repeat', Rewind: 'rewind', RotateCcw: 'rotate-ccw',
    RotateCw: 'rotate-cw', Rss: 'rss', Save: 'save', Scissors: 'scissors', Search: 'search', Send: 'send',
    Server: 'server', Settings: 'settings', Share: 'share', Share2: 'share-2', ShieldOff: 'shield-off', Shield: 'shield',
    ShoppingBag: 'shopping-bag', ShoppingCart: 'shopping-cart', Shuffle: 'shuffle', Sidebar: 'sidebar',
    SkipBack: 'skip-back', SkipForward: 'skip-forward', Slack: 'slack', Slash: 'slash', Sliders: 'sliders',
    Smartphone: 'smartphone', Smile: 'smile', Speaker: 'speaker', Square: 'square', Star: 'start', StopCircle: 'stop-circle',
    Sun: 'sun', Sunrise: 'sunrise', Sunset: 'sunset', Table: 'table', Tablet: 'tablet', Tag: 'tag', Target: 'target',
    Terminal: 'target', Thermometer: 'thermometer', ThumbsDown: 'thumbs-down', ThumbsUp: 'thumbs-up',
    ToggleLeft: 'toggle-left', ToggleRight: 'toggle-right', Tool: 'tool', Trash: 'trash', Trash2: 'trash-2',
    Trello: 'trello', TrendingDown: 'trending-down', TrendingUp: 'trending-up', Triangle: 'triangle', Truck: 'truck',
    Tv: 'tv', Twitch: 'twitch', Twitter: 'twitter', Type: 'type', Umbrella: 'umbrella', Underline: 'underline',
    Unlock: 'unlock', Upload: 'upload', UploadCloud: 'upload-cloud', UserCheck: 'user-check', UserMinus: 'user-minus',
    UserPlus: 'user-plus', UserX: 'user-x', User: 'user', Users: 'users', VideoOff: 'video-off', Video: 'video',
    Voicemail: 'voicemail', Volume: 'volume', Volume1: 'volume-1', Volume2: 'volume-2', VolumeX: 'volume-x', Watch: 'watch',
    WifiOff: 'wifi-off', Wifi: 'wifi', Wind: 'wind', XCircle: 'x-circle', XOctagon: 'x-octagon', XSquare: 'x-square',
    X: 'x', Youtube: 'youtube', ZapOff: 'zap-off', Zap: 'zap', ZoomIn: 'zoom-in', ZoomOut: 'zoom-out' }) as const;
export const COLORS = Object.freeze({ Blue60: "#0400D5", Blue50: "#0500FF", Grayscale95: "#0A0C0F",
    Grayscale80: "#1A2026", Grayscale60: "#2B3233", Grayscale50: "#3A434D", Grayscale40: "#737A80",
    Grayscale25: "#DADBDE", Grayscale20: "#E7E8EA", Grayscale10: "#F5F6F9", Grayscale05: "#FAFAFA",
    Grayscale00: "#FFFFFF" }) as const;
export const ANIMATION_STATES = Object.freeze({ Backward: -1, Initial: 0, Forward: 1}) as const;
export const DIRECTIONS = Object.freeze({ ToTop: 1, ToRight: 2, ToBottom: 3, ToLeft: 4 }) as const;
